services:
  postgres:
    image: postgres:14-alpine
    container_name: task_postgres
    environment:
      POSTGRES_DB: mini_project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres_db:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - monitoring-network

  postgres_keycloak:
    image: postgres:14-alpine
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5434:5432"
    networks:
      - keycloak-network
    volumes:
      - keycloak_db:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:nightly
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: keycloak_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres_keycloak
    networks:
      - keycloak-network

volumes:
  postgres_db:
  keycloak_db:

networks:
  postgres-network:
    driver: bridge
  keycloak-network:
    driver: bridge
  monitoring-network:
    driver: bridge
