server:
  port: 9092
  error:
    include-stacktrace: never
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_project_db1
    username: postgres
    password: 1234
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

